theme: jekyll-theme-minimal
logo: '/assets/logo.svg'
title: cazomevolve
description: Bioinformatic pipeline to automate augmenting, visualizing, and interrogating large datasets for exploratory analysis of CAZyme-complements.
